### ISSUE TITLE
Function passed to mlx_key_hook() seems to get called twice. [BUG]

### ISSUE THREAD

**Issue by sdxsd** [W2Codam/MLX42#20]
**Description**
Function passed to mlx_key_hook() seems to be called twice, when only 
one key press has occurred. 

**To Reproduce**
```
static void	keycodes(mlx_key_data_t keydata, void *param)
{
	if (param)
		;
	ft_printf("%c\n", keydata.key);
}

int	gameloop(t_reality *reality)
{
	mlx_key_hook(reality -> mlx, keycodes, NULL);
	mlx_loop(reality -> mlx);
	return (TRUE);
}
```
**Expected behavior**
When key is pressed, given function to mlx_key_hook() should only run once. 

**Desktop**
 - OS: Error occurs on MacOS and Arch Linux

Apologies if this issue is caused by a misunderstanding of the use of hooks.

**Comment by FreekBes** [comment]
The `keydata` struct contains an `action` enum, which defines what happened with the key in question. This enum can be set to either `MLX_RELEASE`, `MLX_PRESS` or `MLX_REPEAT`. In your example to reproduce, the key is printed twice, because it prints on both the `MLX_PRESS` and `MLX_RELEASE` action. To only handle key presses, simply add an if statement to your code:

```C
static void	keycodes(mlx_key_data_t keydata, void *param)
{
	if (param)
		;
	if (keydata.action == MLX_PRESS)
		ft_printf("%c\n", keydata.key);
}

int	gameloop(t_reality *reality)
{
	mlx_key_hook(reality -> mlx, keycodes, NULL);
	mlx_loop(reality -> mlx);
	return (TRUE);
}
```

**Comment by sdxsd** [comment]
Ah that makes sense, thank you. I'll close the issue!
